In [6]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [7]:
df = pd.read_csv('ecom.csv')
df.head()

,Product ID,Cost of Production ($),Competition Level (1-5),Target Audience,Market Conditions,Desired Profit Margin (%),Actual Price ($)
0,1,12700,4,Teenagers,Stable,23,15504.0
1,2,8600,2,Professionals,Growing,27,10922.0
2,3,15400,3,Seniors,Competitive,20,17640.0
3,4,9800,4,Young Adults,Stable,25,12040.0
4,5,18700,5,Millennials,Declining,18,13608.6

In [13]:
label_encoder = LabelEncoder()
df['target_audience_encoded'] = label_encoder.fit_transform(df['Target Audience'])
df['market_conditions_encoded'] = label_encoder.fit_transform(df['Market Conditions'])
df.head()

,Product ID,Cost of Production ($),Competition Level (1-5),Target Audience,Market Conditions,Desired Profit Margin (%),Actual Price ($),target_column_encoded,target_audience_encoded,market_conditions_encoded
0,1,12700,4,Teenagers,Stable,23,15504.0,4,4,3
1,2,8600,2,Professionals,Growing,27,10922.0,2,2,2
2,3,15400,3,Seniors,Competitive,20,17640.0,3,3,0
3,4,9800,4,Young Adults,Stable,25,12040.0,5,5,3
4,5,18700,5,Millennials,Declining,18,13608.6,1,1,1